#!/usr/bin/env python3
# Copyright (C) 2024 Timo Salomon for HAW Hamburg, Germany
# This file was automatically generated from omnetpp SDN4CoRE output flowUpdatesStreamCMI.json
# DO NOT EDIT THIS FILE
# 

import sys
from _decimal import Decimal
from networkx import grid_graph
import random
import networkx as nx
import matplotlib.pyplot as plt
from dynamic_reservation.environment.network import Network

def car_topology(linkrate_backbone=10000000000.0, linkrate_nodes=1000000000.0, queuesize=Decimal(sys.float_info.max), output=False, nrCBSqueues=2):
    # create network
    net = Network()

    # create switches
    bridges = ['sw_fl', 'sw_c', 'sw_fr', 'sw_rl', 'sw_rr', ]

    # add switches to network
    net.create_link(nodeA='sw_fl', nodeB='sw_c', priorities=nrCBSqueues, queue_in=queuesize, rate_out=linkrate_backbone)
    net.create_link(nodeA='sw_c', nodeB='sw_fr', priorities=nrCBSqueues, queue_in=queuesize, rate_out=linkrate_backbone)
    net.create_link(nodeA='sw_c', nodeB='sw_rl', priorities=nrCBSqueues, queue_in=queuesize, rate_out=linkrate_backbone)
    net.create_link(nodeA='sw_c', nodeB='sw_rr', priorities=nrCBSqueues, queue_in=queuesize, rate_out=linkrate_backbone)

    # add hosts
    tsn_devices = ['lidar_fl', 'connectivity_gw', 'zc_fl', 'infotainment', 'camera_front', 'lidar_fr', 'zc_fr', 'camera_rear', 'lidar_rl', 'zc_rl', 'adas', 'zc_rr', 'lidar_rr', ]

    # add hosts to network
    net.create_link(nodeA='lidar_fl', nodeB='sw_fl', priorities=nrCBSqueues, queue_in=queuesize, rate_out=linkrate_nodes)
    net.create_link(nodeA='connectivity_gw', nodeB='sw_fl', priorities=nrCBSqueues, queue_in=queuesize, rate_out=linkrate_nodes)
    net.create_link(nodeA='zc_fl', nodeB='sw_fl', priorities=nrCBSqueues, queue_in=queuesize, rate_out=linkrate_nodes)
    net.create_link(nodeA='infotainment', nodeB='sw_fl', priorities=nrCBSqueues, queue_in=queuesize, rate_out=linkrate_nodes)
    net.create_link(nodeA='camera_front', nodeB='sw_fr', priorities=nrCBSqueues, queue_in=queuesize, rate_out=linkrate_nodes)
    net.create_link(nodeA='lidar_fr', nodeB='sw_fr', priorities=nrCBSqueues, queue_in=queuesize, rate_out=linkrate_nodes)
    net.create_link(nodeA='zc_fr', nodeB='sw_fr', priorities=nrCBSqueues, queue_in=queuesize, rate_out=linkrate_nodes)
    net.create_link(nodeA='camera_rear', nodeB='sw_rl', priorities=nrCBSqueues, queue_in=queuesize, rate_out=linkrate_nodes)
    net.create_link(nodeA='lidar_rl', nodeB='sw_rl', priorities=nrCBSqueues, queue_in=queuesize, rate_out=linkrate_nodes)
    net.create_link(nodeA='zc_rl', nodeB='sw_rl', priorities=nrCBSqueues, queue_in=queuesize, rate_out=linkrate_nodes)
    net.create_link(nodeA='adas', nodeB='sw_rr', priorities=nrCBSqueues, queue_in=queuesize, rate_out=linkrate_backbone)
    net.create_link(nodeA='zc_rr', nodeB='sw_rr', priorities=nrCBSqueues, queue_in=queuesize, rate_out=linkrate_nodes)
    net.create_link(nodeA='lidar_rr', nodeB='sw_rr', priorities=nrCBSqueues, queue_in=queuesize, rate_out=linkrate_nodes)

    if output:
        nx.draw_planar(net.graph, with_labels=True)
        plt.show()

    return net.graph, bridges, tsn_devices
