#!/usr/bin/env python3
# Copyright (C) 2024 Timo Salomon for HAW Hamburg, Germany
# This file was automatically generated from omnetpp SDN4CoRE inifile shaping.ini
# DO NOT EDIT THIS FILE
# 

from _decimal import Decimal
from networkx import grid_graph
import networkx as nx

def set_car_gcls(graph_state):
    # create gcl list
    gcls = []

    nx.set_edge_attributes(graph_state['simple_graph'], {('zc_fl', 'sw_fl'): {'gcl': (Decimal(0.001), Decimal(0.000017))}})
    nx.set_edge_attributes(graph_state['simple_graph'], {('adas', 'sw_rr'): {'gcl': (Decimal(0.001), Decimal(0.000017))}})
    nx.set_edge_attributes(graph_state['simple_graph'], {('sw_fl', 'sw_c'): {'gcl': (Decimal(0.001), Decimal(0.000017))}})
    nx.set_edge_attributes(graph_state['simple_graph'], {('sw_fl', 'zc_fl'): {'gcl': (Decimal(0.001), Decimal(0.000017))}})
    nx.set_edge_attributes(graph_state['simple_graph'], {('sw_fr', 'zc_fr'): {'gcl': (Decimal(0.001), Decimal(0.000020))}})
    nx.set_edge_attributes(graph_state['simple_graph'], {('sw_c', 'sw_fl'): {'gcl': (Decimal(0.001), Decimal(0.000017))}})
    nx.set_edge_attributes(graph_state['simple_graph'], {('sw_c', 'sw_rr'): {'gcl': (Decimal(0.001), Decimal(0.000017))}})
    nx.set_edge_attributes(graph_state['simple_graph'], {('sw_c', 'sw_fr'): {'gcl': (Decimal(0.001), Decimal(0.000021))}})
    nx.set_edge_attributes(graph_state['simple_graph'], {('sw_c', 'sw_rl'): {'gcl': (Decimal(0.001), Decimal(0.000021))}})
    nx.set_edge_attributes(graph_state['simple_graph'], {('sw_rl', 'zc_rl'): {'gcl': (Decimal(0.001), Decimal(0.000020))}})
    nx.set_edge_attributes(graph_state['simple_graph'], {('sw_rr', 'sw_c'): {'gcl': (Decimal(0.001), Decimal(0.000017))}})
    nx.set_edge_attributes(graph_state['simple_graph'], {('sw_rr', 'zc_rr'): {'gcl': (Decimal(0.001), Decimal(0.000020))}})

    return gcls

